import { Category, CustomInterval, Sticker } from '@/types';

export const DEFAULT_CATEGORIES: Omit<
  Category,
  'createdAt' | 'updatedAt'
>[] = [
  {
    id: 'cat-bills',
    name: 'Bills & Finance',
    stickerSetId: 'set-bills',
    color: '#5B8C5A',
    defaultRepeatJson: null,
    sortOrder: 1,
    isSystem: true,
  },
  {
    id: 'cat-health',
    name: 'Health & Medication',
    stickerSetId: 'set-health',
    color: '#C45B7A',
    defaultRepeatJson: null,
    sortOrder: 2,
    isSystem: true,
  },
  {
    id: 'cat-appointments',
    name: 'Appointments',
    stickerSetId: 'set-appointments',
    color: '#3D7EA6',
    defaultRepeatJson: null,
    sortOrder: 3,
    isSystem: true,
  },
  {
    id: 'cat-birthdays',
    name: 'Birthdays & Anniversaries',
    stickerSetId: 'set-birthdays',
    color: '#C97B9B',
    defaultRepeatJson: null,
    sortOrder: 4,
    isSystem: true,
  },
  {
    id: 'cat-subscriptions',
    name: 'Subscriptions',
    stickerSetId: 'set-subscriptions',
    color: '#6B7FD7',
    defaultRepeatJson: null,
    sortOrder: 5,
    isSystem: true,
  },
  {
    id: 'cat-vehicle',
    name: 'Vehicle & Home',
    stickerSetId: 'set-vehicle',
    color: '#8B6B4A',
    defaultRepeatJson: null,
    sortOrder: 6,
    isSystem: true,
  },
  {
    id: 'cat-work',
    name: 'Work',
    stickerSetId: 'set-work',
    color: '#4A6FA5',
    defaultRepeatJson: null,
    sortOrder: 7,
    isSystem: true,
  },
  {
    id: 'cat-water',
    name: 'Drink Water',
    stickerSetId: 'set-water',
    color: '#3D9ECD',
    defaultRepeatJson: JSON.stringify({ every: 2, unit: 'hours' } satisfies CustomInterval),
    sortOrder: 8,
    isSystem: true,
  },
  {
    id: 'cat-stretch',
    name: 'Stretch',
    stickerSetId: 'set-stretch',
    color: '#5BA88A',
    defaultRepeatJson: JSON.stringify({ every: 2, unit: 'hours' } satisfies CustomInterval),
    sortOrder: 9,
    isSystem: true,
  },
  {
    id: 'cat-travel',
    name: 'Travel',
    stickerSetId: 'set-travel',
    color: '#D4A017',
    defaultRepeatJson: null,
    sortOrder: 10,
    isSystem: true,
  },
];

export const DEFAULT_STICKERS: Omit<Sticker, 'createdAt'>[] = [
  { id: 'stk-bills', categoryId: 'cat-bills', name: 'Wallet', assetKey: 'bills', emoji: '💳' },
  { id: 'stk-health', categoryId: 'cat-health', name: 'Pill', assetKey: 'health', emoji: '💊' },
  { id: 'stk-appointments', categoryId: 'cat-appointments', name: 'Calendar', assetKey: 'appointments', emoji: '📅' },
  { id: 'stk-birthdays', categoryId: 'cat-birthdays', name: 'Cake', assetKey: 'birthdays', emoji: '🎂' },
  { id: 'stk-subscriptions', categoryId: 'cat-subscriptions', name: 'Refresh', assetKey: 'subscriptions', emoji: '🔄' },
  { id: 'stk-vehicle', categoryId: 'cat-vehicle', name: 'Home', assetKey: 'vehicle', emoji: '🏠' },
  { id: 'stk-work', categoryId: 'cat-work', name: 'Briefcase', assetKey: 'work', emoji: '💼' },
  { id: 'stk-water', categoryId: 'cat-water', name: 'Water Glass', assetKey: 'water', emoji: '💧' },
  { id: 'stk-stretch', categoryId: 'cat-stretch', name: 'Stretch', assetKey: 'stretch', emoji: '🧘' },
  { id: 'stk-travel', categoryId: 'cat-travel', name: 'Luggage', assetKey: 'travel', emoji: '✈️' },
  { id: 'stk-star', categoryId: null, name: 'Star', assetKey: 'star', emoji: '⭐' },
  { id: 'stk-bell', categoryId: null, name: 'Bell', assetKey: 'bell', emoji: '🔔' },
  { id: 'stk-heart', categoryId: null, name: 'Heart', assetKey: 'heart', emoji: '💖' },
  { id: 'stk-check', categoryId: null, name: 'Check', assetKey: 'check', emoji: '✅' },
];

export const DEFAULT_SETTINGS = {
  theme: 'system' as const,
  defaultReminderTime: '09:00',
  defaultSnoozeMinutes: 5,
  notificationSound: 'default',
  enableNlCreate: true,
  enableSuggestions: true,
  enableDailyBrief: true,
  onboardingDone: false,
};
